### ISSUE TITLE
Add images for temperature sensor and thermostat to overview image

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse-workshop#10]

**Comment by lulf** [comment]
@ppatierno Maybe having a modified variant of https://github.com/ppatierno/enmasse-iot-demo/blob/master/images/demo_deployment_spark_os.png would be even better!

**Comment by ppatierno** [comment]
@lulf don't worry ! I'll take care about that ! ;)

**Comment by ppatierno** [comment]
Closing on 32701402e40f6f157e16680172bf5578c971fed8
