### ISSUE TITLE
EnMasse console asks for credentials

### ISSUE THREAD

**Issue by ppatierno** [EnMasseProject/enmasse-workshop#23]
@lulf with latest update to 0.19.0 trying to access to the EnMasse console asks me credentials (it didn't happen before but the authentication page with OpenShift button was showed).

**Comment by lulf** [comment]
@ppatierno I'm not sure what you mean. Does it not redirrect you to the 'keycloak' page with the openshift button? Do you use the workshop playbook?

**Comment by ppatierno** [comment]
@lulf Yes I used the playbook and when I click on the console route, it shows me pop up asking for username and passoword and not the page with OpenShift button anymore.

**Comment by lulf** [comment]
@ppatierno I think I fixed the issue now

**Comment by lulf** [comment]
@ppatierno Basically I committed some unintended changes before to remove some details about the playground cluster.
